create extension if not exists pgcrypto;
create type public.app_role as enum('administrator','staff','requester');
create type public.equipment_status as enum('Available','Borrowed','Maintenance');
create type public.request_status as enum('Pending','Approved','Rejected','Released','Returned','Overdue','Closed');
create type public.maintenance_status as enum('Pending','In Progress','Resolved','Rejected');

create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,email text,full_name text not null default 'Unnamed User',role public.app_role not null default 'requester',created_at timestamptz default now());
create table public.equipment(id bigint generated by default as identity primary key,asset_code text unique not null,name text not null,category text not null,condition text not null default 'Good',status public.equipment_status not null default 'Available',created_at timestamptz default now());
create table public.borrowing_requests(id bigint generated by default as identity primary key,equipment_id bigint references public.equipment(id) not null,requester_id uuid references public.profiles(id) not null,purpose text not null,start_at timestamptz not null,expected_return_at timestamptz not null,status public.request_status default 'Pending',reviewed_by uuid references public.profiles(id),reviewed_at timestamptz,released_at timestamptz,returned_at timestamptz,closed_at timestamptz,created_at timestamptz default now(),check(expected_return_at>start_at));
create table public.maintenance_requests(id bigint generated by default as identity primary key,equipment_id bigint references public.equipment(id) not null,requester_id uuid references public.profiles(id) not null,description text not null,status public.maintenance_status default 'Pending',created_at timestamptz default now(),resolved_at timestamptz);
create table public.audit_logs(id bigint generated by default as identity primary key,user_id uuid references public.profiles(id),action text not null,module text not null,record_id bigint,description text not null,created_at timestamptz default now());

create or replace function public.ensure_profile() returns public.profiles language plpgsql security definer set search_path=public as $$
declare p public.profiles;
begin
if auth.uid() is null then raise exception 'You must be signed in';end if;
select * into p from public.profiles where id=auth.uid();
if not found then
insert into public.profiles(id,email,full_name,role)
values(auth.uid(),auth.jwt()->>'email',coalesce(nullif(auth.jwt()->>'name',''),split_part(coalesce(auth.jwt()->>'email','User'),'@',1)),'requester')
returning * into p;
end if;
return p;
end$$;
grant execute on function public.ensure_profile() to authenticated;

create or replace function public.current_role() returns public.app_role language sql stable security definer set search_path=public as $$select role from public.profiles where id=auth.uid()$$;
create or replace function public.write_audit(a text,m text,r bigint,d text) returns void language plpgsql security definer set search_path=public as $$begin insert into public.audit_logs(user_id,action,module,record_id,description) values(auth.uid(),a,m,r,d);end$$;

create or replace function public.create_maintenance_request(p_equipment_id bigint,p_description text) returns bigint language plpgsql security definer set search_path=public as $$
declare i bigint;
begin
if public.current_role() not in('administrator','staff') then raise exception 'Only Administrator or Laboratory Staff may add maintenance requests';end if;
if nullif(trim(p_description),'') is null then raise exception 'Description is required';end if;
if not exists(select 1 from public.equipment where id=p_equipment_id) then raise exception 'Equipment not found';end if;
insert into public.maintenance_requests(equipment_id,requester_id,description) values(p_equipment_id,auth.uid(),trim(p_description)) returning id into i;
update public.equipment set status='Maintenance' where id=p_equipment_id;
perform public.write_audit('CREATED','Maintenance',i,'Created maintenance request');
return i;
end$$;
grant execute on function public.create_maintenance_request(bigint,text) to authenticated;

create or replace function public.submit_borrowing_request(p_equipment_id bigint,p_purpose text,p_start_at timestamptz,p_expected_return_at timestamptz) returns bigint language plpgsql security definer set search_path=public as $$
declare i bigint;s public.equipment_status;c text;begin
select id,status,asset_code into i,s,c from public.equipment where id=p_equipment_id for update;
if i is null then raise exception 'Equipment not found';end if;
if s<>'Available' then raise exception 'Only available equipment may be requested';end if;
if p_expected_return_at<=p_start_at then raise exception 'Invalid dates';end if;
insert into public.borrowing_requests(equipment_id,requester_id,purpose,start_at,expected_return_at) values(p_equipment_id,auth.uid(),p_purpose,p_start_at,p_expected_return_at) returning id into i;
perform public.write_audit('SUBMITTED','Borrowing',i,'Submitted borrowing request for '||c);return i;end$$;

create or replace function public.approve_borrowing_request(p_request_id bigint) returns void language plpgsql security definer set search_path=public as $$
declare s public.request_status;r uuid;c text;begin
if public.current_role()<>'administrator' then raise exception 'Only Administrator may approve requests';end if;
select br.status,br.requester_id,e.asset_code into s,r,c from public.borrowing_requests br join public.equipment e on e.id=br.equipment_id where br.id=p_request_id for update;
if s<>'Pending' then raise exception 'Only Pending requests may be approved';end if;if r=auth.uid() then raise exception 'You cannot approve your own request';end if;
update public.borrowing_requests set status='Approved',reviewed_by=auth.uid(),reviewed_at=now() where id=p_request_id;
perform public.write_audit('APPROVED','Borrowing',p_request_id,'Approved borrowing request for '||c);end$$;

create or replace function public.reject_borrowing_request(p_request_id bigint) returns void language plpgsql security definer set search_path=public as $$
declare s public.request_status;r uuid;c text;begin
if public.current_role()<>'administrator' then raise exception 'Only Administrator may reject requests';end if;
select br.status,br.requester_id,e.asset_code into s,r,c from public.borrowing_requests br join public.equipment e on e.id=br.equipment_id where br.id=p_request_id for update;
if s<>'Pending' then raise exception 'Only Pending requests may be rejected';end if;if r=auth.uid() then raise exception 'You cannot reject your own request';end if;
update public.borrowing_requests set status='Rejected',reviewed_by=auth.uid(),reviewed_at=now() where id=p_request_id;
perform public.write_audit('REJECTED','Borrowing',p_request_id,'Rejected borrowing request for '||c);end$$;

create or replace function public.release_borrowing_request(p_request_id bigint) returns void language plpgsql security definer set search_path=public as $$
declare s public.request_status;ei bigint;es public.equipment_status;c text;begin
if public.current_role() not in('administrator','staff') then raise exception 'Operation not permitted';end if;
select br.status,br.equipment_id,e.status,e.asset_code into s,ei,es,c from public.borrowing_requests br join public.equipment e on e.id=br.equipment_id where br.id=p_request_id for update;
if s<>'Approved' then raise exception 'Only Approved requests may be released';end if;if es<>'Available' then raise exception 'Equipment is not available';end if;
update public.borrowing_requests set status='Released',released_at=now() where id=p_request_id;update public.equipment set status='Borrowed' where id=ei;perform public.write_audit('RELEASED','Borrowing',p_request_id,'Released equipment '||c);end$$;

create or replace function public.return_borrowing_request(p_request_id bigint) returns void language plpgsql security definer set search_path=public as $$
declare s public.request_status;ei bigint;co text;c text;begin
if public.current_role() not in('administrator','staff') then raise exception 'Operation not permitted';end if;
select br.status,br.equipment_id,e.condition,e.asset_code into s,ei,co,c from public.borrowing_requests br join public.equipment e on e.id=br.equipment_id where br.id=p_request_id for update;
if s not in('Released','Overdue') then raise exception 'Only Released or Overdue may be returned';end if;
update public.borrowing_requests set status='Returned',returned_at=now() where id=p_request_id;
update public.equipment set status=case when lower(co) in('damaged','needs repair') then 'Maintenance' else 'Available' end where id=ei;
perform public.write_audit('RETURNED','Borrowing',p_request_id,'Returned equipment '||c);end$$;

create or replace function public.create_equipment(p_asset_code text,p_name text,p_category text,p_condition text) returns bigint language plpgsql security definer set search_path=public as $$declare i bigint;begin if public.current_role()<>'administrator' then raise exception 'Only Administrator may manage equipment';end if;insert into public.equipment(asset_code,name,category,condition) values(p_asset_code,p_name,p_category,p_condition) returning id into i;perform public.write_audit('CREATED','Equipment',i,'Created equipment '||p_asset_code);return i;end$$;

create or replace function public.update_equipment(p_equipment_id bigint,p_asset_code text,p_name text,p_category text,p_condition text) returns void language plpgsql security definer set search_path=public as $$begin
if public.current_role()<>'administrator' then raise exception 'Only Administrator may manage equipment';end if;
update public.equipment set asset_code=trim(p_asset_code),name=trim(p_name),category=trim(p_category),condition=trim(p_condition) where id=p_equipment_id;
if not found then raise exception 'Equipment not found';end if;
perform public.write_audit('UPDATED','Equipment',p_equipment_id,'Updated equipment');
end$$;
grant execute on function public.update_equipment(bigint,text,text,text,text) to authenticated;

create or replace function public.update_user_role(p_user_id uuid,p_role public.app_role) returns void language plpgsql security definer set search_path=public as $$begin
if public.current_role()<>'administrator' then raise exception 'Only Administrator may manage users';end if;
if not exists(select 1 from public.profiles where id=p_user_id) then raise exception 'User not found';end if;
update public.profiles set role=p_role where id=p_user_id;
perform public.write_audit('UPDATED','Users',null,'Updated user role');
end$$;
grant execute on function public.update_user_role(uuid,public.app_role) to authenticated;

create or replace function public.update_maintenance_status(p_request_id bigint,p_status public.maintenance_status) returns void language plpgsql security definer set search_path=public as $$declare ei bigint;begin
if public.current_role()<>'administrator' then raise exception 'Only Administrator may manage maintenance';end if;
select equipment_id into ei from public.maintenance_requests where id=p_request_id;
if ei is null then raise exception 'Maintenance request not found';end if;
update public.maintenance_requests set status=p_status,resolved_at=case when p_status='Resolved' then now() else null end where id=p_request_id;
if p_status='Resolved' then update public.equipment set status='Available' where id=ei; end if;
perform public.write_audit('UPDATED','Maintenance',p_request_id,'Updated maintenance status to '||p_status);
end$$;
grant execute on function public.update_maintenance_status(bigint,public.maintenance_status) to authenticated;

alter table public.profiles enable row level security;alter table public.equipment enable row level security;alter table public.borrowing_requests enable row level security;alter table public.maintenance_requests enable row level security;alter table public.audit_logs enable row level security;
create policy profiles_read on public.profiles for select to authenticated using(id=auth.uid() or public.current_role()='administrator');
create policy equipment_read on public.equipment for select to authenticated using(true);
create policy equipment_admin on public.equipment for all to authenticated using(public.current_role()='administrator') with check(public.current_role()='administrator');
create policy requests_read on public.borrowing_requests for select to authenticated using(requester_id=auth.uid() or public.current_role() in('administrator','staff'));
create policy requests_insert on public.borrowing_requests for insert to authenticated with check(requester_id=auth.uid() and status='Pending');
create policy maintenance_read on public.maintenance_requests for select to authenticated using(requester_id=auth.uid() or public.current_role() in('administrator','staff'));
create policy audit_admin on public.audit_logs for select to authenticated using(public.current_role()='administrator');
revoke update,delete on public.borrowing_requests from authenticated;revoke insert,update,delete on public.audit_logs from authenticated;
